apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc.yaml
- deployment.yaml
- service.yaml

secretGenerator:
- name: trusted-ca
  files:
  - etcd-cert/ca.pem
generatorOptions:
  disableNameSuffixHash: true
