apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  multicluster-etcd-pvc
  labels:
    app: multicluster-etcd
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
